platform :ios, '9.3'
target 'ViroSample' do
  use_frameworks!
  pod 'ViroReact', :path => '../node_modules/react-viro/ios/'
  pod 'ViroKit', :path => '../node_modules/react-viro/ios/dist/ViroRenderer/'
  pod 'RCT3DModel', :path => '../node_modules/react-native-3d-model-view'

  pod 'RNZipArchive', :path => '../node_modules/react-native-zip-archive'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

end
